services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
      POSTGRES_DB: n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5679:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_password

      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5679/

      GENERIC_TIMEZONE: America/Lima
      TZ: America/Lima
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  python-api:
    build: ./api
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./templates:/app/templates

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - python-api
      - n8n